### ISSUE TITLE
Avoid using low port numbers

### ISSUE THREAD

**Issue by mattfbacon** [lino-levan/word-you-rather#1]
Ports <~8080 are generally "dangerous" to use because of conflicts with other applications. 3000, the port you happened to use in this case IS above the 1024 system reserved port space, which is nice, but it is rather small.

I recommend picking a more standard port (like 8080) or one that isn't on this list: https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers.

Hope you resolve this soon because I am unable to use this due to Alt-N MDaemon webmail server running on port 3000.

**Comment by lino-levan** [comment]
Apologies, I have now fixed this issue. It was actually already patched, I just didn't update the readme.

**Comment by mattfbacon** [comment]
So sorry to continue bothering you but my DevOps team objects to the new port 8888 as it conflicts with our deployment of EMC2 (Legato) Sun Solcitice Backup.
